# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  fatsDir: '$(system.defaultWorkingDirectory)/fats'
  fatsRefspec: b65bc2f1d14a80d9d9793e96766bc1d1b19508a4 # projectriff/fats master as of 2019-04-30
  cnabRiffDir: '$(system.defaultWorkingDirectory)/cnab-riff'
  cnabRiffRefspec: 6e962bfbbdee1300ee913f06c89c03bb86fd0ea4 # projectriff/cnab-riff master as of 2019-05-10

pool:
  vmImage: 'ubuntu-16.04'

name: $(Date:yyyyMMdd)$(Rev:.r)
steps:
  - template: ci/go-build-step.yml
  - script: make
    workingDirectory: '$(modulePath)'
    displayName: 'build and unit test'

  - bash: bash <(curl -s https://codecov.io/bash)
    workingDirectory: '$(modulePath)'
    displayName: 'publish code coverage'

  - template: ci/fetch-fats-step.yml
  - template: ci/start-minikube-steps.yml
  - template: ci/install-kubectl-steps.yml

  - template: ci/fetch-cnab-riff-step.yml

  - script: |
      ./cnab/app/run
    workingDirectory: '$(modulePath)'
    displayName: 'run install'
    env:
      CNAB_ACTION: install
      MANIFEST_FILE: $(cnabRiffDir)/cnab/app/kab/manifest.yaml
      LOG_LEVEL: debug
      TARGET_REGISTRY: registry.kube-system.svc.cluster.local

  - bash: ci/diagnostics.sh
    condition: failed()
    displayName: 'diagnostics'

  - template: ci/publish-docker-image-steps.yml
